TAPHOME_PLATFORM = "taphome"

TAPHOME_API_SERVICE = f"{TAPHOME_PLATFORM}_TapHomeApiService"
TAPHOME_COORDINATOR = f"{TAPHOME_PLATFORM}_Coordinator"
TAPHOME_DEVICES = f"{TAPHOME_PLATFORM}_Devices"
TAPHOME_LANGUAGE = f"{TAPHOME_PLATFORM}_language"
CONF_CORES = "cores"
CONF_LANGUAGE = "language"
CONF_API_URL = "api_url"
CONF_UPDATE_INTERVAL = "update_interval"
CONF_CLIMATES = "climates"
CONF_FAN = "fans"
CONF_HUMIDIFIER = "humidifiers"
CONF_VALVE = "valves"
CONF_MULTIVALUE_SWITCHES = "multivalue_switches"
CONF_BUTTONS = "buttons"
USE_DESCRIPTION_AS_ENTITY_ID = "use_description_as_entity_id"
USE_DESCRIPTION_AS_NAME = "use_description_as_name"
