name: python-check
on:
  workflow_call:
    inputs:
      name:
        description: "name of the step, e.g. 'ruff check'"
        required: false
        type: string
      package:
        description: "step dependencies, which will be installed before running the command. e.g. 'ruff mypy'"
        required: false
        type: string
      command:
        description: "command to run, e.g. 'ruff check .'"
        required: true
        type: string

jobs:
  run-check:
    name: ${{ inputs.name || inputs.package || inputs.command }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python -m pip install --upgrade pip
      - run: pip install homeassistant
      - if: ${{ inputs.package != '' }}
        run: pip install ${{ inputs.package }}
      - run: ${{ inputs.command }}
