name: Remove old artifacts

on:
  workflow_dispatch:
  schedule:
    # Every day at 1am
    - cron: '0 3 * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # For private repos
    permissions:
      actions: write

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1.4.0
      with:
        age: '2 days' # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
        skip-recent: 5
